### ISSUE TITLE
Sorular?

### ISSUE THREAD

**Issue by omrumbakitemiz** [UniversityClubSystem/ClubSystem.Web#3]
Her türlü soru burada sorulup çözüme kavuşturulacak.

**Comment by omrumbakitemiz** [comment]
Şu anki backend tasarımında güvenlik JWT ile sağlanmakta. Kullanıcı kayıt olduğunda bilgiler doğrulandıktan sonra ön yüze cevap olarak JWT token dönmekte. Burada birkaç soru ortaya çıkmakta:
- Kayıt işleminden sonra kullanıcıya JWT token geri dönmeli mi?
- Token dönmeli ise bu demek oluyor ki, kullanıcı sanki normal yolla sisteme giriş yapmış gibi doğrudan ana sayfaya yönlendirilmeli.(giriş yapmış bir şekilde)
- Token dönmemesi gerekiyorsa bu sefer kullanıcı giriş sayfasına(login) yönlendirilmeli ve giriş yaptıktan sonra cevap olarak token almalı ardından ana sayfaya yönlendirilmeli.

TL;DR
- Kullanıcı kayıt olduktan sonra otomatik olarak giriş yapılıp ana sayfaya mı yönlendirilmeli yoksa giriş ekranından(login) giriş mi yapmalı?

**Comment by f9n** [comment]
> Kullanıcı kayıt olduktan sonra otomatik olarak giriş yapılıp ana sayfaya mı yönlendirilmeli yoksa giriş ekranından(login) giriş mi yapmalı?

Giriş ekranından(login) giriş yapilmasi daha doğru olur. :+1:
